// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpmcfsoukzipobzjkzyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwbWNmc291a3ppcG9iemprenlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODIwMDIsImV4cCI6MjA3MTA1ODAwMn0.-nVq1li65q1sVZmSIAKER4OGSgmD0ObTQdFu-7f1n6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});